name: Gitee repos mirror periodic job

on:
  push:
    pull_request:
      paths:
      - '.github/workflows/**'
      # Runs at every pull requests submitted in master branch 
      branches: [ master ]
    schedule:
      # Runs at 01:00 UTC (9:00 AM Beijing) every day
      - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hub Mirror Action.
      uses: Yikun/hub-mirror-action@v0.08
      with:
        #  需要被同步的源端账户名，如github/phpdragon，表示Github的phpdragon账户。
        src: github/Python
        # 需要同步到的目的端账户名，如gitee/phpdragon，表示Gitee的phpdragon账户。
        dst: gitee/Python
        # 用于目的端上传代码的SSH key，用于上传代码
        dst_key: ${{ secrets.GITEE_SYNC }}
        # 强制更新
        force_update: true
        # clone方式，使用http、ssh方式进行clone
        clone_style: "ssh"
